# 1. Build
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
# Dependencies
COPY pom.xml .
RUN mvn dependency:go-offline
# Packages
COPY src ./src
RUN mvn clean package -DskipTests

# 2. Runtime
FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]